// <auto-generated />
namespace Capa_Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Migración_Tablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migración_Tablas));
        
        string IMigrationMetadata.Id
        {
            get { return "202403181628409_Migración_Tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
